var estilos=[
    ["Color","#000000"],
    ["Fuentes","Comic Sans MS","Times New Roman","Arial","Calibri",
    "xx-small","x-small","small","medium","large","x-large","xx-large",
    "normal","bold","lighter","bolder",
    "normal","italic","oblique",
    "normal","no-common-ligatures proportional-nums","common-ligatures tabular-nums","small-caps slashed-zero"],
    ["Text Align","start","end","center","justify"],
    ["Line height","Number","em","porciento","px"],
    ["Text decoration","solid","double","dotted","dashed","wavy"],
    ["Text transform","capitalize","uppercase","lowercase","none","full-width","full-size-kana"],
    ["Vertical align","baseline","topV","middle","bottom","sub","text-top"],
    ["Text indent","Número","Porcentaje","em"],
    ["Letter spacing","rem","px"],
    ["White space","normal","nowrap","pre","pre-wrap","pre-line","break-spaces"]
]

var color,
    tamano="medium",
    bandTamano=0,
    weight="normal",
    estiloFuente="normal",
    varianteFuente="normal",
    justificadoVar="start",
    bandAltura=0,
    altura,
    decoration="solid",
    posicionLinea,
    colorDecoration,
    contenido="",
    conjuntoLineas,
    transformacionV,
    vertical,
    indentV,
    valorSpacing,
    spaceV,
    pie
